name: React Ecommerce App CI/CD

on :
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: #Continuous Integration 
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
       - name: Checkout code
         uses: action/checkout@v2

      # Step 2: Set up Node.js
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
            node-version: '20'
        
      #Step 3: install dependencies
       - name: Install dependencies
         run: npm install

      #Step 4: Run tests
       - name: Run tests
         run: npm test

      #Step 5: build React app
       - name: Build React app
         run: npm run build
